/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GiftService } from "../gift.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GiftCreateInput } from "./GiftCreateInput";
import { Gift } from "./Gift";
import { Request } from "../../request/base/Request";
import { GiftFindManyArgs } from "./GiftFindManyArgs";
import { GiftWhereUniqueInput } from "./GiftWhereUniqueInput";
import { GiftUpdateInput } from "./GiftUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GiftControllerBase {
  constructor(
    protected readonly service: GiftService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Gift })
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: GiftCreateInput,
  })
  async createGift(@common.Body() data: GiftCreateInput): Promise<Gift> {
    return await this.service.createGift({
      data: data,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        recipient: true,
        sender: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Gift] })
  @ApiNestedQuery(GiftFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async gifts(@common.Req() request: Request): Promise<Gift[]> {
    const args = plainToClass(GiftFindManyArgs, request.query);
    return this.service.gifts({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        recipient: true,
        sender: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Gift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async gift(
    @common.Param() params: GiftWhereUniqueInput
  ): Promise<Gift | null> {
    const result = await this.service.gift({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        recipient: true,
        sender: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Gift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: GiftUpdateInput,
  })
  async updateGift(
    @common.Param() params: GiftWhereUniqueInput,
    @common.Body() data: GiftUpdateInput
  ): Promise<Gift | null> {
    try {
      return await this.service.updateGift({
        where: params,
        data: data,
        select: {
          amount: true,
          createdAt: true,
          id: true,
          recipient: true,
          sender: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Gift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGift(
    @common.Param() params: GiftWhereUniqueInput
  ): Promise<Gift | null> {
    try {
      return await this.service.deleteGift({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          id: true,
          recipient: true,
          sender: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
