/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Invite } from "./Invite";
import { InviteCountArgs } from "./InviteCountArgs";
import { InviteFindManyArgs } from "./InviteFindManyArgs";
import { InviteFindUniqueArgs } from "./InviteFindUniqueArgs";
import { CreateInviteArgs } from "./CreateInviteArgs";
import { UpdateInviteArgs } from "./UpdateInviteArgs";
import { DeleteInviteArgs } from "./DeleteInviteArgs";
import { Event } from "../../event/base/Event";
import { User } from "../../user/base/User";
import { InviteService } from "../invite.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Invite)
export class InviteResolverBase {
  constructor(
    protected readonly service: InviteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Invite",
    action: "read",
    possession: "any",
  })
  async _invitesMeta(
    @graphql.Args() args: InviteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Invite])
  @nestAccessControl.UseRoles({
    resource: "Invite",
    action: "read",
    possession: "any",
  })
  async invites(@graphql.Args() args: InviteFindManyArgs): Promise<Invite[]> {
    return this.service.invites(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Invite, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Invite",
    action: "read",
    possession: "own",
  })
  async invite(
    @graphql.Args() args: InviteFindUniqueArgs
  ): Promise<Invite | null> {
    const result = await this.service.invite(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Invite)
  @nestAccessControl.UseRoles({
    resource: "Invite",
    action: "create",
    possession: "any",
  })
  async createInvite(@graphql.Args() args: CreateInviteArgs): Promise<Invite> {
    return await this.service.createInvite({
      ...args,
      data: {
        ...args.data,

        event: args.data.event
          ? {
              connect: args.data.event,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Invite)
  @nestAccessControl.UseRoles({
    resource: "Invite",
    action: "update",
    possession: "any",
  })
  async updateInvite(
    @graphql.Args() args: UpdateInviteArgs
  ): Promise<Invite | null> {
    try {
      return await this.service.updateInvite({
        ...args,
        data: {
          ...args.data,

          event: args.data.event
            ? {
                connect: args.data.event,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Invite)
  @nestAccessControl.UseRoles({
    resource: "Invite",
    action: "delete",
    possession: "any",
  })
  async deleteInvite(
    @graphql.Args() args: DeleteInviteArgs
  ): Promise<Invite | null> {
    try {
      return await this.service.deleteInvite(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Event, {
    nullable: true,
    name: "event",
  })
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "read",
    possession: "any",
  })
  async getEvent(@graphql.Parent() parent: Invite): Promise<Event | null> {
    const result = await this.service.getEvent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Invite): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
